version: "3.9"

services:
  docker-cwa:
    image: "docker-cwa:0.1"
    volumes:
      - ./volumes/docker-cwa/config:/app/config
    ports:
      - "1234:1234"
    depends_on:
      - docker-api

  docker-api:
    image: "docker-api:0.1"
    volumes:
      - ./volumes/docker-api/config:/app/config
    ports:
      - "3000:3000"
